# Numpy (Numerical Python)

- It's a python library used for working with arrays. An array is like a list, but it can store large amounts of data much more efficiently.
- Python lists can be slow and take up more memory when working with large data but Numpy helps solve this problem by:
    - Storing data efficiently.
    - Performing calculations faster.
    - Offering built-in functions for common mathematical and statistical operations.
- Arrays are important in data science because they allow you to store data in two-dimensional or multi-dimensional forms, similar to rows and columns in a spreadsheet.
- Numpy arrays can be used to perform operations on entire arrays at once, instead of looping through elements one by one.

In [87]:
import numpy as np

In [88]:
e = [i for i in range(2, 50) if i % 2 == 0]
o = [i for i in range(2, 50) if i % 2 != 0]

print(e)
print(o)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48]
[3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49]


In [89]:
# summing two list
a = e + o
print(a)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49]


In [90]:
r = []
for i in range(len(e)):
    r.append(e[i] + o[i])

print(r)

[5, 9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65, 69, 73, 77, 81, 85, 89, 93, 97]


In [91]:
m = []
for i in range(len(e)):
    m.append(e[i] * o[i])

print(m)

[6, 20, 42, 72, 110, 156, 210, 272, 342, 420, 506, 600, 702, 812, 930, 1056, 1190, 1332, 1482, 1640, 1806, 1980, 2162, 2352]


In [7]:
# using list comprehension, elements of two lists can be paired using a zip() function.

n = [x * y for x, y in zip(e, o)]
print(n)

[6, 20, 42, 72, 110, 156, 210, 272, 342, 420, 506, 600, 702, 812, 930, 1056, 1190, 1332, 1482, 1640, 1806, 1980, 2162, 2352]


In [93]:
len(n)

24

In [94]:
r[6]

29

## Creating an array

In [95]:
np.array([4, 50, 15, 34, 23, 2, 12, 3, 11, 10])

array([ 4, 50, 15, 34, 23,  2, 12,  3, 11, 10])

In [96]:
b = np.array(e)
d = np.array(o)

print(b)
print(d)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
[ 3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49]


In [97]:
b + d

array([ 5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65, 69,
       73, 77, 81, 85, 89, 93, 97])

In [98]:
b * d

array([   6,   20,   42,   72,  110,  156,  210,  272,  342,  420,  506,
        600,  702,  812,  930, 1056, 1190, 1332, 1482, 1640, 1806, 1980,
       2162, 2352])

In [99]:
b/d

array([0.66666667, 0.8       , 0.85714286, 0.88888889, 0.90909091,
       0.92307692, 0.93333333, 0.94117647, 0.94736842, 0.95238095,
       0.95652174, 0.96      , 0.96296296, 0.96551724, 0.96774194,
       0.96969697, 0.97142857, 0.97297297, 0.97435897, 0.97560976,
       0.97674419, 0.97777778, 0.9787234 , 0.97959184])

## Array Operations

In [100]:
np.sum([b])

np.int64(600)

In [101]:
np.sum([d])

np.int64(624)

In [102]:
np.mean([b])

np.float64(25.0)

In [103]:
np.mean([d])

np.float64(26.0)

In [104]:
y = b/d
y

array([0.66666667, 0.8       , 0.85714286, 0.88888889, 0.90909091,
       0.92307692, 0.93333333, 0.94117647, 0.94736842, 0.95238095,
       0.95652174, 0.96      , 0.96296296, 0.96551724, 0.96774194,
       0.96969697, 0.97142857, 0.97297297, 0.97435897, 0.97560976,
       0.97674419, 0.97777778, 0.9787234 , 0.97959184])

In [105]:
# to summarize the decimals
y = np.around(y, decimals = 3)  
print(y)

[0.667 0.8   0.857 0.889 0.909 0.923 0.933 0.941 0.947 0.952 0.957 0.96
 0.963 0.966 0.968 0.97  0.971 0.973 0.974 0.976 0.977 0.978 0.979 0.98 ]


In [106]:
y.shape

(24,)

### Array Dimensions
Axes: Directions along which the data is arranged.
   - 1D has 1 axis
   - 2D has 2 axes: rows and columns.
   - 3D has 3 axes: layers, rows and columns.

In [107]:
np.array([b, d])

array([[ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
        34, 36, 38, 40, 42, 44, 46, 48],
       [ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
        35, 37, 39, 41, 43, 45, 47, 49]])

In [108]:
np.array([b, d]).shape

(2, 24)

In [109]:
np.array([b, d]).size

48

In [110]:
np.array([b, d]).ndim

2

In [111]:
n = np.array([[b], [d], [o]])
n

array([[[ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
         34, 36, 38, 40, 42, 44, 46, 48]],

       [[ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
         35, 37, 39, 41, 43, 45, 47, 49]],

       [[ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
         35, 37, 39, 41, 43, 45, 47, 49]]])

In [112]:
print(n.shape)
print(n.ndim)
print(n.size)

(3, 1, 24)
3
72


In [113]:
a = np.array([b, d])

In [114]:
print(a.shape)
print(a.ndim)
print(a.size)
print("\n", a)

(2, 24)
2
48

 [[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
 [ 3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49]]


In [115]:
c = np.array([b, d, o])

In [116]:
print(c.shape)
print(c.ndim)
print(c.size)
print("\n", c)

(3, 24)
2
72

 [[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
 [ 3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49]
 [ 3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49]]


In [117]:
f = np.array([[1, 3, 5, 7, 9, 11, 13, 15, 17, 19], [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]])

print(f.shape)
print(f.ndim)
print(f.size)
print("\n", f)

(2, 10)
2
20

 [[ 1  3  5  7  9 11 13 15 17 19]
 [ 2  4  6  8 10 12 14 16 18 20]]


In [118]:
g = np.array([[1, 3, 5, 7, 9, 11, 13, 15, 17, 19], [2, 4, 6, 8, 10, 12, 14, 16, 18, 20], [21, 23, 25, 27, 29, 31, 33, 35, 37, 39]])

print(g.shape)
print(g.ndim)
print(g.size)
print("\n", g)

(3, 10)
2
30

 [[ 1  3  5  7  9 11 13 15 17 19]
 [ 2  4  6  8 10 12 14 16 18 20]
 [21 23 25 27 29 31 33 35 37 39]]


In [119]:
k = np.array([[1, 3, 5, 7, 9], [11, 13, 15, 17, 19], [2, 4, 6, 8, 10], [12, 14, 16, 18, 20], [21, 23, 25, 27, 29], [31, 33, 35, 37, 39]])
print(k.shape)
print(k.ndim)
print(k.size)
print("\n", k)

(6, 5)
2
30

 [[ 1  3  5  7  9]
 [11 13 15 17 19]
 [ 2  4  6  8 10]
 [12 14 16 18 20]
 [21 23 25 27 29]
 [31 33 35 37 39]]


In [120]:
h = np.array([[1, 3, 5, 7, 9, 11, 13, 15, 17, 19], [2, 4, 6, 8, 10, 12, 14, 16, 18, 20], [21, 23, 25, 27, 29, 31, 33, 35, 37, 39], [22, 24, 26, 28, 30, 32, 34, 36, 38, 40]])
print(h.shape)
print(h.ndim)
print(h.size)
print("\n", h)

(4, 10)
2
40

 [[ 1  3  5  7  9 11 13 15 17 19]
 [ 2  4  6  8 10 12 14 16 18 20]
 [21 23 25 27 29 31 33 35 37 39]
 [22 24 26 28 30 32 34 36 38 40]]


In [121]:
i = np.array([[1, 3, 5, 7, 9] , [11, 13, 15, 17, 19], [2, 4, 6, 8, 10], [12, 14, 16, 18, 20], [21, 23, 25, 27, 29], [31, 33, 35, 37, 39], [22, 24, 26, 28, 30], [32, 34, 36, 38, 40]])

print(i.shape)
print(i.ndim)
print(i.size)
print("\n", i)

(8, 5)
2
40

 [[ 1  3  5  7  9]
 [11 13 15 17 19]
 [ 2  4  6  8 10]
 [12 14 16 18 20]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [22 24 26 28 30]
 [32 34 36 38 40]]


In [122]:
l = np.array([[[1, 3, 5, 7, 9] , [11, 13, 15, 17, 19], [2, 4, 6, 8, 10]], [[12, 14, 16, 18, 20], [21, 23, 25, 27, 29], [31, 33, 35, 37, 39]]])
print(l.shape)
print(l.ndim)
print(l.size)
print("\n", l)

(2, 3, 5)
3
30

 [[[ 1  3  5  7  9]
  [11 13 15 17 19]
  [ 2  4  6  8 10]]

 [[12 14 16 18 20]
  [21 23 25 27 29]
  [31 33 35 37 39]]]


In [123]:
m = np.array([[1, 3, 5, 7, 9, 11, 13, 15, 17, 19], [2, 4, 6, 8, 10, 12, 14, 16, 18, 20], [21, 23, 25, 27, 29, 31, 33, 35, 37, 39], [22, 24, 26, 28, 30, 32, 34, 36, 38, 40]])
print(m.shape)
print(m.ndim)
print(m.size)
print("\n", m)

(4, 10)
2
40

 [[ 1  3  5  7  9 11 13 15 17 19]
 [ 2  4  6  8 10 12 14 16 18 20]
 [21 23 25 27 29 31 33 35 37 39]
 [22 24 26 28 30 32 34 36 38 40]]


In [124]:
j = np.array([[7, 8, 9, 8, 0], [8, 6, 5, 78, 9]])
print(j.shape)
print(j.ndim)
print(j.size)
print("\n",j)

(2, 5)
2
10

 [[ 7  8  9  8  0]
 [ 8  6  5 78  9]]


In [125]:
p = np.array([[[1, 3, 5, 7, 9], [11, 13, 15, 17, 19]], [[2, 4, 6, 8, 10], [12, 14, 16, 18, 20]], [[21, 23, 25, 27, 29], [31, 33, 35, 37, 39]], [[22, 24, 26, 28, 30], [32, 34, 36, 38, 40]]])
print(p.shape)
print(p.ndim)
print(p.size)
print("\n", p)

(4, 2, 5)
3
40

 [[[ 1  3  5  7  9]
  [11 13 15 17 19]]

 [[ 2  4  6  8 10]
  [12 14 16 18 20]]

 [[21 23 25 27 29]
  [31 33 35 37 39]]

 [[22 24 26 28 30]
  [32 34 36 38 40]]]


In [126]:
# to create a 2D array with 20 elements (4 rows and 5 columns)
q = np.arange(20).reshape(4, 5)
print(q)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [127]:
np.arange(1, 37).reshape(6,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

## List of Data types in Numpy and the Characters used to represent them
- S - string
- i - integer
- b - boolean
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O -object
- u - unsigned number
- U - unicode string
- V - fixed chunk of memory for other types (void)
    - size can be determined for i, u, f, S and U

In [128]:
# to get the data type of an array 
q.dtype

dtype('int64')

In [129]:
v = np.array([1, 2, 3, 4], dtype = "S")
print(v)

[b'1' b'2' b'3' b'4']


In [130]:
v.dtype

dtype('S1')

In [131]:
# data type conversion
v.astype(int)

array([1, 2, 3, 4])

## Some important Numpy methods
**1. Creating Array**
- np.array(): to create a numpy array from a python list or tuple
- np.zeros(), np.ones(), np.full(): create array filled with zeros, ones or a specific value.
- np.arange(), np.linespace(): create arrays of evenly spaced values.

In [132]:
np.array([[3, 6, 8, 9, 7, 5], [7, 2, 8.0, 9.7, 4, 12]])

array([[ 3. ,  6. ,  8. ,  9. ,  7. ,  5. ],
       [ 7. ,  2. ,  8. ,  9.7,  4. , 12. ]])

In [133]:
np.zeros((3, 15))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [134]:
np.ones((4, 10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [135]:
np.full((3, 8), 8)

array([[8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8]])

In [136]:
np.full((3, 4, 4,), 10)

array([[[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]],

       [[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]],

       [[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]]])

In [137]:
np.arange(1, 25, 3) # [start, stop, step]

array([ 1,  4,  7, 10, 13, 16, 19, 22])

In [139]:
z = np.linspace(2, 10, 10) # [start, stop, num_points]

In [140]:
z

array([ 2.        ,  2.88888889,  3.77777778,  4.66666667,  5.55555556,
        6.44444444,  7.33333333,  8.22222222,  9.11111111, 10.        ])

In [141]:
z = np.around(z, decimals = 3)

In [142]:
z

array([ 2.   ,  2.889,  3.778,  4.667,  5.556,  6.444,  7.333,  8.222,
        9.111, 10.   ])

**2. Reshaping and Manipulating arrays**
- np.reshape(): reshapes an array without changing its data.
- np.ravel(), np.flatten(): convert multi dimensional arrays into 1D arrays, ravel() returns a view, flatten() returns a copy.
- np.transpose(): reverses or permutes the axes of an array, often used with matrices.

In [143]:
np.arange(1, 25, 3).reshape(2, 4)

array([[ 1,  4,  7, 10],
       [13, 16, 19, 22]])

In [144]:
np.arange(1, 25).reshape(2, 12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [145]:
np.ravel(l)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19,  2,  4,  6,  8, 10, 12, 14,
       16, 18, 20, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39])

In [146]:
l.flatten()

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19,  2,  4,  6,  8, 10, 12, 14,
       16, 18, 20, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39])

In [147]:
x = np.arange(0, 100).reshape(2, 5, 10)

In [148]:
x

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

In [149]:
np.ravel(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [150]:
x.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [156]:
l.shape

(2, 3, 5)

In [155]:
l.ndim

3

In [158]:
np.transpose(l)

array([[[ 1, 12],
        [11, 21],
        [ 2, 31]],

       [[ 3, 14],
        [13, 23],
        [ 4, 33]],

       [[ 5, 16],
        [15, 25],
        [ 6, 35]],

       [[ 7, 18],
        [17, 27],
        [ 8, 37]],

       [[ 9, 20],
        [19, 29],
        [10, 39]]])

In [157]:
np.transpose(l).shape

(5, 3, 2)

In [151]:
xy = np.arange(0, 100).reshape(10, 2, 5)

In [152]:
xy

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]],

       [[70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79]],

       [[80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89]],

       [[90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [153]:
np.ravel(xy)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [154]:
xy.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [159]:
print(xy.shape)
print(xy.ndim)
print(xy.size)

(10, 2, 5)
3
100


In [160]:
np.transpose(xy)

array([[[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95]],

       [[ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
        [ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96]],

       [[ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92],
        [ 7, 17, 27, 37, 47, 57, 67, 77, 87, 97]],

       [[ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93],
        [ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98]],

       [[ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94],
        [ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99]]])

In [161]:
np.transpose(xy).shape

(5, 2, 10)

In [162]:
x.transpose()

array([[[ 0, 50],
        [10, 60],
        [20, 70],
        [30, 80],
        [40, 90]],

       [[ 1, 51],
        [11, 61],
        [21, 71],
        [31, 81],
        [41, 91]],

       [[ 2, 52],
        [12, 62],
        [22, 72],
        [32, 82],
        [42, 92]],

       [[ 3, 53],
        [13, 63],
        [23, 73],
        [33, 83],
        [43, 93]],

       [[ 4, 54],
        [14, 64],
        [24, 74],
        [34, 84],
        [44, 94]],

       [[ 5, 55],
        [15, 65],
        [25, 75],
        [35, 85],
        [45, 95]],

       [[ 6, 56],
        [16, 66],
        [26, 76],
        [36, 86],
        [46, 96]],

       [[ 7, 57],
        [17, 67],
        [27, 77],
        [37, 87],
        [47, 97]],

       [[ 8, 58],
        [18, 68],
        [28, 78],
        [38, 88],
        [48, 98]],

       [[ 9, 59],
        [19, 69],
        [29, 79],
        [39, 89],
        [49, 99]]])

In [163]:
x.transpose().shape

(10, 5, 2)

**3. Basic Math and Stats Operations**
- np.sum(), np.mean(), np.median(): compute the sum, mean, and median of an array.
- np.max(), np.min(), np.argmax(), np.argmin(): find the maximum, minimum values and their indices in an array.
- np.cumsum(), np.cumprod(): return the cumulative sum or product along an array.

In [ ]:
xy

In [165]:
x.std()

np.float64(28.86607004772212)

In [166]:
np.sum(x)

np.int64(4950)

In [167]:
xy.sum()

np.int64(4950)

In [168]:
# summing two arrays
b+d

array([ 5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65, 69,
       73, 77, 81, 85, 89, 93, 97])

In [169]:
# adding a number to every element in an array - vectorization
b + 10

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44,
       46, 48, 50, 52, 54, 56, 58])

In [170]:
# indexing
b[2] + d[0]

np.int64(9)

In [171]:
b[4] + b[23]

np.int64(58)

In [172]:
xy.min()

np.int64(0)

In [ ]:
# argmin() gives you the index of the minimum number in an array
xy.argmin()

np.int64(0)

In [173]:
xy.max()

np.int64(99)

In [175]:
xy.argmax()

np.int64(99)

In [ ]:
# argmax() gives you the index of the highest number in the array
b.argmax()

np.int64(23)

In [178]:
b[23]

np.int64(48)

In [ ]:
# cumsum() stands for cummulative sum used in statistical analysis and sums items in an arrray cummulatively.
b.cumsum()

array([  2,   6,  12,  20,  30,  42,  56,  72,  90, 110, 132, 156, 182,
       210, 240, 272, 306, 342, 380, 420, 462, 506, 552, 600])

In [183]:
i = np.arange(0, 100)

In [184]:
i

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [185]:
i.cumsum()

array([   0,    1,    3,    6,   10,   15,   21,   28,   36,   45,   55,
         66,   78,   91,  105,  120,  136,  153,  171,  190,  210,  231,
        253,  276,  300,  325,  351,  378,  406,  435,  465,  496,  528,
        561,  595,  630,  666,  703,  741,  780,  820,  861,  903,  946,
        990, 1035, 1081, 1128, 1176, 1225, 1275, 1326, 1378, 1431, 1485,
       1540, 1596, 1653, 1711, 1770, 1830, 1891, 1953, 2016, 2080, 2145,
       2211, 2278, 2346, 2415, 2485, 2556, 2628, 2701, 2775, 2850, 2926,
       3003, 3081, 3160, 3240, 3321, 3403, 3486, 3570, 3655, 3741, 3828,
       3916, 4005, 4095, 4186, 4278, 4371, 4465, 4560, 4656, 4753, 4851,
       4950])

In [187]:
# cumprod() stands for cummulative product and it used in statistical analysis to multiply items in an array cummulatively.
b.cumprod()

array([                   2,                    8,                   48,
                        384,                 3840,                46080,
                     645120,             10321920,            185794560,
                 3715891200,          81749606400,        1961990553600,
             51011754393600,     1428329123020800,    42849873690624000,
        1371195958099968000, -8719569645729742848,  -309857993208365056,
        6672140331791679488,  8631196239733456896, -6424639405385842688,
       -5982972731333804032,  1484415464288288768, -2535034009000345600])

In [186]:
i.cumprod()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [189]:
type(b)

numpy.ndarray

In [190]:
# b = np.array(b, dtype = np.float64)

In [ ]:
# b.cumprod()

**4. Sorting and Logical Operations**
- np.sort()
- np.where(): Returns the indices of elements that satisfy a condition.
- np.any() and np.all(): Tests whether any or all elements of an array evaluate to True.

In [200]:
b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])

In [ ]:
d

In [193]:
np.sort(b)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])

In [196]:
np.sort(y)

array([0.667, 0.8  , 0.857, 0.889, 0.909, 0.923, 0.933, 0.941, 0.947,
       0.952, 0.957, 0.96 , 0.963, 0.966, 0.968, 0.97 , 0.971, 0.973,
       0.974, 0.976, 0.977, 0.978, 0.979, 0.98 ])

In [202]:
# find the index of the element 30 
np.where(b == 30)

(array([14]),)

In [208]:
np.where(b > 44)

(array([22, 23]),)

In [206]:
b[22]

np.int64(46)

In [207]:
b[23]

np.int64(48)

In [214]:
q

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [217]:
np.where(q > 8)

(array([1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3]),
 array([4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]))

In [ ]:
First array (array([1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3]), dtype = int64): are the row indices where the conditions q > 8 is true.
Second array (array([4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]), dtype = int64): are the column indices where the condition is true.

q[1, 4] = 
q[]